server:
  port: 1999
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: serkafidanci@gmail.com
    password: yzdl vyzs lpjn apid
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: MAILSERVICE
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}