server:
  port: 8990
spring:
  application:
    name: SATBANA-WAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/auth/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

satbana:
  secret-hash: "At$iV^?eJ|v,R:z<@Fsx^&]+9.(T=g8nyHQW_gtQ6mRTZ>c?b5%e<&G~"
  randomStringBase: "ABCDEFGHIJKLMNOPRSTUVYZQWabcdefghijklmnoprstuvyzqw1234567890+/="
  expiresin: 604800000
  redishash: "SellTheFuckingThingToMe"

jwtfilter:
  exclude:
    paths: "/auth;"

userservice: "http://USER-SERVICE/user/getUserById/"
